config/routes.rb
Rails.application.routes.draw do
  resources :user_events
  resources :events
  resources :users
  post 'user_events/change_state', :to => 'user_events#change_state', :as => 'change_state'
  root "events#welcome"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  has_rich_text :description
  has_many :user_events, dependent: :delete_all
  has_many :users, through: :user_events

  validate :date_cannot_be_in_the_past
  validates :name, presence: { message: "El campo nombre es requerido." }
  validates :date, presence: { message: "El campo fecha es requerido." }
  validates :description, presence: { message: "El campo descripción es requerido." }

  def date_cannot_be_in_the_past
    if date.present? && date < Date.today
      errors.add(:date_past, "La fecha es incorrecta.")
    end
  end  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_events, dependent: :delete_all

    validates :email, presence: true
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]


  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Se ha creado el evento correctamente." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Se ha eliminado el evento correctamente." }
      format.json { head :no_content }
    end
  end

  def welcome 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :date, :description)
    end


end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController
  before_action :set_user_event, only: %i[ show edit update destroy]

  # GET /user_events or /user_events.json
  def index
    @user_events = UserEvent.all
  end

  # GET /user_events/1 or /user_events/1.json
  def show
  end

  # GET /user_events/new
  def new
    @user_event = UserEvent.new
  end

  # GET /user_events/1/edit
  def edit
  end

  # POST /user_events or /user_events.json
  def create
    @user = User.find_by_email(user_event_params[:email])
    puts @user
    if @user.nil?
      puts "no existe el usuario"
      @user = User.new(name: "", email: user_event_params[:email])
      @user.save
      puts "Se crea el nuevo usuario"
    end
    @user_event = UserEvent.new(user_id: @user.id, event_id: user_event_params[:event_id], state: "No responde")

    respond_to do |format|
      if @user_event.save
        format.html { redirect_to user_events_url, notice: "Se ha creado la invitación correctamente." }
      format.json { head :no_content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_events/1 or /user_events/1.json
  def update
    respond_to do |format|
      if @user_event.update(user_event_params)
        format.html { redirect_to user_event_url(@user_event), notice: "User event was successfully updated." }
        format.json { render :show, status: :ok, location: @user_event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_events/1 or /user_events/1.json
  def destroy
    @user_event.destroy

    respond_to do |format|
      format.html { redirect_to user_events_url, notice: "Se ha eliminado la invitación correctamente." }
      format.json { head :no_content }
    end
  end

  def change_state
    @user_event = UserEvent.find_by_id(params[:id])
    if @user_event
      if @user_event.state == "No responde"
        @user_event.update(state: params[:new_state])
        respond_to do |format|
          format.html { redirect_to user_events_url, notice: "Se ha actualizado el estado de la invitación." }
          format.json { head :no_content }
        end
      else
        respond_to do |format|
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user_event.errors, status: :unprocessable_entity }
        end
      end
    else
      render status: :not_found, json: { error: "UserEvent no encontrado" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_event
      @user_event = UserEvent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_event_params
      params.require(:user_event).permit(:user_id, :event_id, :state, :email)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Name:</strong>
    <%= event.name %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= event.date %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

</div>

app/views/events/_form.html.erb
  <div class="row justify-content-center align-items-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <%= form_with(model: event) do |f| %>
            <div class="mb-3">
              <%= f.label :name, "Nombre del evento", { class: "my-3" } %>
              <%= f.text_field :name, class: "form-control" %>
              <% if event.errors.messages.any? %>
                <% if event.errors.messages.key?(:name) %>
                  <div class="text-danger">
                    <%= event.errors.messages[:name][0] %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div class="mb-3">
              <%= f.label :date, class: "my-3" %>
              <%= f.date_field :date, class: "form-control" %>
              <% if event.errors.messages.any? %>
                <% if event.errors.messages.key?(:date) %>
                  <div class="text-danger">
                    <%= event.errors.messages[:date][0] %>
                  </div>
                <% end %>
                <% if event.errors.messages.key?(:date_past) %>
                  <div class="text-danger">
                    <%= event.errors.messages[:date_past][0] %>
                  </div>
                <% end %>
              <% end %>
            </div>

            <div class="mb-3">
              <%= f.label :description, class: "my-3" %>
              <%= f.rich_text_area :description, class: "form-control" %>
              <% if event.errors.messages.any? %>
                <% if event.errors.messages.key?(:description) %>
                  <div class="text-danger">
                    <%= event.errors.messages[:description][0] %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div class="text-center">
              <%= f.submit "Crear Evento", class: "btn btn-primary mt-4" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="row my-4 py-4 mb-1">
    <div class="col-sm-12 d-flex justify-content-center">
      <h1 class="text-center display-2">Eventos</h1>.
    </div>
  </div>

  <div class="row mx-5">
    <div class="col-sm-11 d-flex justify-content-end">
      <%= link_to "Crear Evento", new_event_path, class: "btn btn-success" %>

    </div>
  </div>

  <div class="row my-4 py-4 justify-content-center">
    <div class="col-sm-9 d-flex justify-content-center">
      <table class="table table-striped table-hover center">
        <thead>
          <tr class="table-dark">
            <th>Nombre del evento</th>
            <th>Fecha</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
            <tr>

              <td><%= event.name %></td>
              <td><%= event.date %></td>
              <td>
                <div class="d-flex align-items-center">
                  <%= link_to "Ver Evento", event, class: "btn btn-outline-primary mx-1" %>
                  <%= button_to "Eliminar",
                  event,
                  method: :delete,
                  class: "btn btn-outline-danger mx-1" %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <br>

</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row my-4 py-4 mb-2 pb-2">
    <div class="col-sm-12 d-flex justify-content-center">
      <h1 class="text-center display-2">Crear nuevo evento</h1>.
    </div>
  </div>


  <%= render "form", event: @event %>

  <br>

  <div class="row mt-3 pt-3 mb-4">
    <div class="col-sm-12 d-flex justify-content-center">
      <%= link_to "Volver", events_path %>
    </div>
  </div>

</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="row my-4 py-4 mb-1 pb-2">
    <div class="col-sm-12 d-flex justify-content-center">
      <h1 class="text-center display-2"><p class="fw-bold"><%= @event.name %></h1></p>
    </div>
  </div>

  <div class="row my-3 py-4 justify-content-center">
    <div class="col-sm-12 d-flex justify-content-center">
      <div class="card w-75">
        <div class="card-header">
          Descripción del evento
        </div>
        <div class="card-body">
        <div class="card-body text-dark">
          <p class="card-text fw-bold">
            Fecha: <%= @event.date %>
          </p>
          <div class="trix-content my-3">
            <%= @event.description %>
          </div>
          <%= link_to "Crear Invitación", new_user_event_path, class: "btn btn-success my-2" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-3 pt-3 mb-4">
    <div class="col-sm-12 d-flex justify-content-center">
      <%= link_to "Volver", events_path %>
    </div>
  </div>

    

</div>

app/views/events/welcome.erb
<div class="container-fluid mt-4 pt-4"> 
    <div class="row mt-5 pt-5">
            <div class="col-sm-12 d-flex justify-content-center">
                <h1 class="text-center display-1">INVIT-APP</h1>.
        </div>
    </div>
    
    <div class="row mt-5 justify-content-center">


        <div class="col-sm-9 d-flex justify-content-center">
            <div class="d-flex justify-content-between"> 
                <%= link_to "Ver Eventos", events_path, :class => "btn btn-primary btn-lg mx-3" %>
                <%= link_to "Crear Eventos", new_event_path, :class => "btn btn-primary btn-lg mx-3" %>
                <%= link_to "Ver Invitaciones", user_events_path, :class => "btn btn-primary btn-lg mx-3" %>
            </div>
        </div>
    </div>

</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invitationsapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> 
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <%= link_to "Invitapp", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <div class="nav-link"><%= link_to "Ver Eventos", events_path , class:"nav-link"%></div>
            </li>
            <li class="nav-item">
              <div class="nav-link"><%= link_to "Crear Eventos", new_event_path , class:"nav-link"%></div>
            </li>
            <li class="nav-item">
              <div class="nav-link"><%= link_to "Ver Invitaciones", user_events_path , class:"nav-link"%></div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/user_events/_form.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center">
    <div class="col-md-6">
          <div class="row mx-3">
      <div class="col-sm-12 d-flex justify-content-end  mx-5">
          <%= link_to "Crear Evento", new_event_path, class: "btn btn-success"%>

      </div>
    </div>
      <%= form_with(model: user_event) do |f|%>
        <div class="mb-3">
          <%= f.label :event_id, "Selecciona un evento", class:"my-3"%>
          <%= f.select :event_id, options_for_select(Event.all.map{|e| [e.name, e.id]}), {}, {class: "form-select"} %>
        </div>
        <div class="mb-3">
          <%= f.label :email, "Correo electrónico del invitado", class:"my-3" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="text-center">
          <%= f.submit "Enviar Invitación", class: "btn btn-primary mt-4" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user_events/_user_event.html.erb
<div id="<%= dom_id user_event %>">
  <p>
    <strong>User:</strong>
    <%= user_event.user_id %>
  </p>

  <p>
    <strong>Event:</strong>
    <%= user_event.event_id %>
  </p>

  <p>
    <strong>Type state:</strong>
    <%= user_event.state %>
  </p>

</div>

app/views/user_events/edit.html.erb
<h1>Editing user event</h1>

<%= render "form", user_event: @user_event %>

<br>

<div>
  <%= link_to "Show this user event", @user_event %> |
  <%= link_to "Back to user events", user_events_path %>
</div>

app/views/user_events/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="row my-4 py-4 mb-1">
    <div class="col-sm-12 d-flex justify-content-center">
      <h1 class="text-center display-2">Invitaciones Enviadas</h1>.
    </div>
  </div>

    <div class="row mx-5">
      <div class="col-sm-12 d-flex justify-content-end">
          <%= link_to "Crear Invitación", new_user_event_path, class: "btn btn-success"%>

      </div>
    </div>

  <div class="row my-4 py-4">
    <div class="col-sm-12 d-flex justify-content-center">
      <table class="table table-striped table-hover">
        <thead>
          <tr class="table-dark">
            <th>Nombre del evento</th>
            <th>Invitado</th>
            <th>Estado de la Invitación</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @user_events.each do |user_event| %>
            <tr>
              
              <td><%= user_event.event.name %></td>
              <td><%= user_event.user.email %></td>
              <td><%= user_event.state %></td>
              <td>
                <div class="d-flex align-items-center">
                <%= link_to "Ver Invitación", user_event, class:"btn btn-outline-primary mx-1" %>
                <%= button_to "Eliminar", user_event, method: :delete, class:"btn btn-outline-danger mx-1"%>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
    <br>



  </div>

app/views/user_events/new.html.erb
<div class="container"> 
    <div class="row my-4 py-4 mb-2 pb-2">
            <div class="col-sm-12 d-flex justify-content-center">
                <h1 class="text-center display-2">Invitar personas</h1>.
        </div>
    </div>



<%= render "form", user_event: @user_event %>

<br>

    <div class="row mt-3 pt-3 mb-4">
            <div class="col-sm-12 d-flex justify-content-center">
                <%= link_to "Volver", user_events_path %>
        </div>
    </div>

</div>

app/views/user_events/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="row my-4 py-4 mb-1 pb-1">
    <div class="col-sm-12 d-flex justify-content-center mb-0">
      <h1 class="text-center display-2"><p class="fw-bold">Invitación</h1></p>
    </div>
  </div>

  <div class="row mt-1 pt-1 my-3 py-4 justify-content-center">
    <div class="col-sm-12 d-flex justify-content-center">
      <div class="card w-75">
        <div class="card-header">
          Descripción de la invitación
        </div>
        <div class="card-body">
        <div class="card-body text-dark">
          <div class="d-flex mb-2">
            <p class="card-text fw-bold mx-3">
            Evento: 
          </p><%= @user_event.event.name%>
            </div>

            <div class="d-flex mb-2">
            <p class="card-text fw-bold mx-3">
            Fecha: 
          </p><%= @user_event.event.date%>
            </div>

            <div class="d-flex">
            <p class="card-text fw-bold mx-3">
            Invitado: 
          </p><%= @user_event.user.email%>
            </div>

          <div class="d-flex justify-content-center mt-3">
            <% if @user_event.state == "No responde" %>
            <%= button_to 'Asistiré', {:action => "change_state", :id => @user_event.id}, :params => {:new_state => "Asiste"}, :method => :post, class:"btn btn-success my-2 mx-3 p-3" %>
            <%= button_to 'No Asistiré', {:action => "change_state", :id => @user_event.id}, :params => {:new_state => "No asiste"}, :method => :post, class:"btn btn-danger my-2 mx-3 p-3" %>
            <%else%>
              <div class="card">
                <div class="card-body">
                  <p class="card-text">
                    <%= @user_event.state%>
                  </p>
                </div>
              </div>
            <%end%>
            </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-3 pt-3 mb-4">
    <div class="col-sm-12 d-flex justify-content-center">
      <%= link_to "Volver", user_events_path %>
    </div>
  </div>

    

</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>